server:
  servlet:
    context-path: /oap-ws-arty

spring:
  application:
    name: oap-ws-arty


arty:
  storage.service.url: ${API_STORAGE_URL:https://rfrlmabarta01.corp.leroymerlin.com:12080/arty/web-service/prestataireWithDocs}


management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
